name: SignalWire Docs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch

  push:
    branches:
    - main
    # paths:
    #   - custom-path/**
  pull_request:
    branches:
    - main

  #   paths:
  #     - custom-path/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: "Build/push & deploy to swarm"
    # The type of runner that the job will run on
    uses: signalwire/actions-template/.github/workflows/docker-bp.yml@e035f7f3ecfc337aad71810e7283eca07cd60fe5
    with:
      PROJECT_NAME: "freeswitch-docs"
      SWARM_SERVICE: "signalwire-docs_freeswitch-docs"
      PR_MESSAGE: false
      SWARM_DEPLOY: true
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      ENDPOINTID: ${{ secrets.DOCS_ENDPOINT_ID }}
      PORTAINER_API_KEY: ${{ secrets.PORTAINER_API_KEY }}
